// src/components/ui/progress.tsx
import * as React from "react";
import { cn } from "@/lib/utils";

// 将渐变计算移到组件外部，避免每次渲染都创建新函数
const getAutoGradient = (percentage: number) => {
  if (percentage >= 80) {
    // 80-100%: 橙红到红色渐变
    return "bg-gradient-to-r from-orange-500 via-red-500 to-red-600";
  }
  if (percentage >= 60) {
    // 60-80%: 黄色到橙色渐变
    return "bg-gradient-to-r from-yellow-400 via-yellow-500 to-orange-500";
  }
  // 0-60%: 青绿到绿色渐变
  return "bg-gradient-to-r from-emerald-400 via-green-500 to-green-600";
};

const Progress = React.forwardRef<
  HTMLDivElement,
  React.HTMLAttributes<HTMLDivElement> & {
    value?: number;
    max?: number;
    variant?: "default" | "success" | "warning" | "danger" | "muted" | "auto";
  }
>(({ className, value = 0, max = 100, variant = "default", ...props }, ref) => {
  const safeMax = typeof max === "number" && max > 0 ? max : 0;
  const safeValue = typeof value === "number" ? value : 0;
  const percentage =
    safeMax === 0 ? 0 : Math.min(Math.max((safeValue / safeMax) * 100, 0), 100);

  const variantClasses = {
    default: "bg-gradient-to-r from-primary/80 via-primary to-primary/80",
    success: "bg-gradient-to-r from-emerald-400 via-green-500 to-green-600",
    warning: "bg-gradient-to-r from-yellow-400 via-yellow-500 to-orange-500",
    danger: "bg-gradient-to-r from-orange-500 via-red-500 to-red-600",
    muted: "bg-gradient-to-r from-gray-300 via-gray-400 to-gray-500",
    auto: getAutoGradient(percentage),
  };

  const actualVariant = variant === "auto" ? "auto" : variant;

  return (
    <div
      ref={ref}
      className={cn(
        "relative h-2 w-full overflow-hidden rounded-full bg-secondary/50 shadow-inner",
        className
      )}
      {...props}
    >
      <div
        className={cn(
          "h-full w-full flex-1 rounded-full shadow-sm transition-transform duration-150 ease-out",
          variantClasses[actualVariant]
        )}
        style={{
          transform: `translateX(-${100 - percentage}%)`,
        }}
      />
    </div>
  );
});
Progress.displayName = "Progress";

export { Progress };

// src/components/ui/Progress.svelte
<script lang="ts">
  import { cn } from "@/lib/utils";
  import type { HTMLAttributes } from "svelte/elements";

  // 将渐变计算移到组件外部，避免每次渲染都创建新函数
  const getAutoGradient = (percentage: number) => {
    if (percentage >= 80) {
      // 80-100%: 橙红到红色渐变
      return "bg-gradient-to-r from-orange-500 via-red-500 to-red-600";
    }
    if (percentage >= 60) {
      // 60-80%: 黄色到橙色渐变
      return "bg-gradient-to-r from-yellow-400 via-yellow-500 to-orange-500";
    }
    // 0-60%: 青绿到绿色渐变
    return "bg-gradient-to-r from-emerald-400 via-green-500 to-green-600";
  };

  interface Props extends HTMLAttributes<HTMLDivElement> {
    value?: number;
    max?: number;
    variant?: "default" | "success" | "warning" | "danger" | "muted" | "auto";
  }

  let {
    class: className,
    value = 0,
    max = 100,
    variant = "default",
    ...props
  }: Props = $props();

  const safeMax = $derived(typeof max === "number" && max > 0 ? max : 0);
  const safeValue = $derived(typeof value === "number" ? value : 0);
  const percentage = $derived(
    safeMax === 0 ? 0 : Math.min(Math.max((safeValue / safeMax) * 100, 0), 100)
  );

  const actualVariant = $derived(variant === "auto" ? "auto" : variant);

  // 动态计算 variant classes
  const variantClass = $derived.by(() => {
    const variantClasses = {
      default: "bg-gradient-to-r from-primary/80 via-primary to-primary/80",
      success: "bg-gradient-to-r from-emerald-400 via-green-500 to-green-600",
      warning: "bg-gradient-to-r from-yellow-400 via-yellow-500 to-orange-500",
      danger: "bg-gradient-to-r from-orange-500 via-red-500 to-red-600",
      muted:
        "bg-gradient-to-r from-gray-300 via-gray-400 to-gray-500 dark:from-gray-600 dark:via-gray-700 dark:to-gray-800",
      auto: getAutoGradient(percentage),
    };
    return variantClasses[actualVariant];
  });
</script>

<div
  class={cn(
    "relative h-2 w-full overflow-hidden rounded-full bg-secondary/50 shadow-inner",
    className
  )}
  {...props}
>
  <div
    class={cn(
      "h-full w-full flex-1 rounded-full shadow-sm transition-transform duration-150 ease-out",
      variantClass
    )}
    style:transform={`translateX(-${100 - percentage}%)`}
  ></div>
</div>
